<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            [
                'category_id' => 3,
                'name' => 'Dried Fruits Mix',
                'stock' => 100,
                'cost' => 0,
                'price' => 8,
                'compare_price' => null,
                'description' => 'Dried Fruits Mix 50g',
                'image' => 'uploads/products/dried_fruits_mix.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Peach',
                'stock' => 100,
                'cost' => 0,
                'price' => 8,
                'compare_price' => null,
                'description' => 'Peach 50g',
                'image' => 'uploads/products/peach.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Strawberry',
                'stock' => 100,
                'cost' => 0,
                'price' => 9,
                'compare_price' => null,
                'description' => 'Strawberry 50g',
                'image' => 'uploads/products/strawberry.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Kiwi',
                'stock' => 100,
                'cost' => 0,
                'price' => 7,
                'compare_price' => null,
                'description' => 'Kiwi 50g',
                'image' => 'uploads/products/kiwi.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Orange Small',
                'stock' => 100,
                'cost' => 0,
                'price' => 6,
                'compare_price' => null,
                'description' => 'Orange 50g',
                'image' => 'uploads/products/orange.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Orange Big',
                'stock' => 100,
                'cost' => 0,
                'price' => 9,
                'compare_price' => null,
                'description' => 'Orange 100g',
                'image' => 'uploads/products/orange.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Citron',
                'stock' => 100,
                'cost' => 0,
                'price' => 9,
                'compare_price' => null,
                'description' => 'Citron 50g',
                'image' => 'uploads/products/citron.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Egyptian Mango',
                'stock' => 100,
                'cost' => 0,
                'price' => 12,
                'compare_price' => null,
                'description' => 'Egyptian Mango 50g',
                'image' => 'uploads/products/egyptian_mango.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Clementine',
                'stock' => 100,
                'cost' => 0,
                'price' => 9,
                'compare_price' => null,
                'description' => 'Clementine 50g',
                'image' => 'uploads/products/clementine.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Yellow Apple',
                'stock' => 100,
                'cost' => 0,
                'price' => 7,
                'compare_price' => null,
                'description' => 'Yellow Apple 50g',
                'image' => 'uploads/products/yellow_apple.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Indian Mango',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Indian Mango 50g',
                'image' => 'uploads/products/indian_mango.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Banana',
                'stock' => 100,
                'cost' => 0,
                'price' => 7,
                'compare_price' => null,
                'description' => 'Banana 50g',
                'image' => 'uploads/products/banana.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Derrak',
                'stock' => 100,
                'cost' => 0,
                'price' => 8,
                'compare_price' => null,
                'description' => 'Derrak 50g',
                'image' => 'uploads/products/derrak.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Green Apple',
                'stock' => 100,
                'cost' => 0,
                'price' => 7,
                'compare_price' => null,
                'description' => 'Green Apple 50g',
                'image' => 'uploads/products/green_apple.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Apricot',
                'stock' => 100,
                'cost' => 0,
                'price' => 7,
                'compare_price' => null,
                'description' => 'Apricot 50g',
                'image' => 'uploads/products/apricot.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Crispy strawberries dipped in blonde chocolate',
                'stock' => 100,
                'cost' => 0,
                'price' => 9,
                'compare_price' => null,
                'description' => 'Crispy strawberries dipped in blonde chocolate 50g',
                'image' => 'uploads/products/blonde_strawberry.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Crispy strawberries dipped in dark chocolate',
                'stock' => 100,
                'cost' => 0,
                'price' => 9,
                'compare_price' => null,
                'description' => 'Crispy strawberries dipped in dark chocolate 50g',
                'image' => 'uploads/products/dark_strawberry.png',
            ],
            [
                'category_id' => 4,
                'name' => 'Chocolate Icecream',
                'stock' => 100,
                'cost' => 0,
                'price' => 5,
                'compare_price' => null,
                'description' => 'Chocolate Icecream 50g',
                'image' => 'uploads/products/chocolate_icecream.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Small grape leaves stuffed with labneh',
                'stock' => 100,
                'cost' => 0,
                'price' => 5,
                'compare_price' => null,
                'description' => 'Small grape leaves stuffed with labneh',
                'image' => 'uploads/products/grape_leaves.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Large grape leaves stuffed with labneh',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Large grape leaves stuffed with labneh',
                'image' => 'uploads/products/grape_leaves_large.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Green Kochk Baladi',
                'stock' => 100,
                'cost' => 0,
                'price' => 7,
                'compare_price' => null,
                'description' => 'green kochk baladi',
                'image' => 'uploads/products/green_kochk.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Feta mint',
                'stock' => 100,
                'cost' => 0,
                'price' => 7,
                'compare_price' => null,
                'description' => 'Feta mint',
                'image' => 'uploads/products/feta_mint.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Feta spicy',
                'stock' => 100,
                'cost' => 0,
                'price' => 7,
                'compare_price' => null,
                'description' => 'Feta spicy',
                'image' => 'uploads/products/feta_spicy.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Makdous Medium Spice with walnuts',
                'stock' => 100,
                'cost' => 0,
                'price' => 7,
                'compare_price' => null,
                'description' => 'Makdous Medium Spice with walnuts',
                'image' => 'uploads/products/makdous.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Stuffed olives with labneh',
                'stock' => 100,
                'cost' => 0,
                'price' => 7,
                'compare_price' => null,
                'description' => 'Stuffed olives with labneh',
                'image' => 'uploads/products/olive_labneh.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Hot Spices',
                'stock' => 100,
                'cost' => 0,
                'price' => 7,
                'compare_price' => null,
                'description' => 'Hot Spices',
                'image' => 'uploads/products/chatta.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Zaarour Baladi',
                'stock' => 100,
                'cost' => 0,
                'price' => 5,
                'compare_price' => null,
                'description' => 'Zaarour Baladi',
                'image' => 'uploads/products/zaarour.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Honey Mustard',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Honey Mustard',
                'image' => 'uploads/products/mrtaste_honey_mustard.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Strawbery Syrup',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Strawbery Syrup',
                'image' => 'uploads/products/mrtaste_strawberry_syrup.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Passion Fruit',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Passion Fruit',
                'image' => 'uploads/products/mrtaste_passion_fruit.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Dulce Depleche',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Dulce Depleche',
                'image' => 'uploads/products/mrtaste_dulce_depleche.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste American Burger',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste American Burger',
                'image' => 'uploads/products/mrtaste_american_burger.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Ketchup',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Ketchup',
                'image' => 'uploads/products/mrtaste_ketchup.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Curry Ketchup',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Curry Ketchup',
                'image' => 'uploads/products/mrtaste_curry_ketchup.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Steak Sauce',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Steak Sauce',
                'image' => 'uploads/products/mrtaste_steak_sauce.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Blueberry Syrup',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Blueberry Syrup',
                'image' => 'uploads/products/mrtaste_blueberry_syrup.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Creamy Cheese',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Creamy Cheese',
                'image' => 'uploads/products/mrtaste_creamy_cheese.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Four Cheese',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Four Cheese',
                'image' => 'uploads/products/mrtaste_four_cheese.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Creamy Sriracha',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Creamy Sriracha',
                'image' => 'uploads/products/mrtaste_creamy_sriracha.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Cheddar',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Cheddar',
                'image' => 'uploads/products/mrtaste_cheddar.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Italian',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Italian',
                'image' => 'uploads/products/mrtaste_italian.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Onion & Garlic',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Onion & Garlic',
                'image' => 'uploads/products/mrtaste_onion_garlic.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Honey Free',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Honey Free',
                'image' => 'uploads/products/mrtaste_honey_free.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Date Syrup',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Date Syrup',
                'image' => 'uploads/products/mrtaste_date_syrup.png',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
