<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            [
                'category_id' => 3,
                'name' => 'Dried Fruits Mix',
                'stock' => 100,
                'cost' => 0,
                'price' => 8,
                'compare_price' => null,
                'description' => 'Dried Fruits Mix 50g',
                'image' => 'uploads/products/dried_fruits_mix.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Peach',
                'stock' => 100,
                'cost' => 0,
                'price' => 8,
                'compare_price' => null,
                'description' => 'Peach 50g',
                'image' => 'uploads/products/peach.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Strawberry',
                'stock' => 100,
                'cost' => 0,
                'price' => 9,
                'compare_price' => null,
                'description' => 'Strawberry 50g',
                'image' => 'uploads/products/strawberry.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Kiwi',
                'stock' => 100,
                'cost' => 0,
                'price' => 7,
                'compare_price' => null,
                'description' => 'Kiwi 50g',
                'image' => 'uploads/products/kiwi.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Orange Small',
                'stock' => 100,
                'cost' => 0,
                'price' => 6,
                'compare_price' => null,
                'description' => 'Orange 50g',
                'image' => 'uploads/products/orange.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Orange Big',
                'stock' => 100,
                'cost' => 0,
                'price' => 9,
                'compare_price' => null,
                'description' => 'Orange 100g',
                'image' => 'uploads/products/orange.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Citron',
                'stock' => 100,
                'cost' => 0,
                'price' => 9,
                'compare_price' => null,
                'description' => 'Citron 50g',
                'image' => 'uploads/products/citron.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Egyptian Mango',
                'stock' => 100,
                'cost' => 0,
                'price' => 12,
                'compare_price' => null,
                'description' => 'Egyptian Mango 50g',
                'image' => 'uploads/products/egyptian_mango.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Clementine',
                'stock' => 100,
                'cost' => 0,
                'price' => 9,
                'compare_price' => null,
                'description' => 'Clementine 50g',
                'image' => 'uploads/products/clementine.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Yellow Apple',
                'stock' => 100,
                'cost' => 0,
                'price' => 7,
                'compare_price' => null,
                'description' => 'Yellow Apple 50g',
                'image' => 'uploads/products/yellow_apple.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Indian Mango',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Indian Mango 50g',
                'image' => 'uploads/products/indian_mango.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Banana',
                'stock' => 100,
                'cost' => 0,
                'price' => 7,
                'compare_price' => null,
                'description' => 'Banana 50g',
                'image' => 'uploads/products/banana.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Derrak',
                'stock' => 100,
                'cost' => 0,
                'price' => 8,
                'compare_price' => null,
                'description' => 'Derrak 50g',
                'image' => 'uploads/products/derrak.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Green Apple',
                'stock' => 100,
                'cost' => 0,
                'price' => 7,
                'compare_price' => null,
                'description' => 'Green Apple 50g',
                'image' => 'uploads/products/green_apple.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Apricot',
                'stock' => 100,
                'cost' => 0,
                'price' => 7,
                'compare_price' => null,
                'description' => 'Apricot 50g',
                'image' => 'uploads/products/apricot.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Crispy strawberries dipped in blonde chocolate',
                'stock' => 100,
                'cost' => 0,
                'price' => 9,
                'compare_price' => null,
                'description' => 'Crispy strawberries dipped in blonde chocolate 50g',
                'image' => 'uploads/products/blonde_strawberry.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Crispy strawberries dipped in dark chocolate',
                'stock' => 100,
                'cost' => 0,
                'price' => 9,
                'compare_price' => null,
                'description' => 'Crispy strawberries dipped in dark chocolate 50g',
                'image' => 'uploads/products/dark_strawberry.png',
            ],
            [
                'category_id' => 4,
                'name' => 'Chocolate Icecream',
                'stock' => 100,
                'cost' => 0,
                'price' => 5,
                'compare_price' => null,
                'description' => 'Chocolate Icecream 50g',
                'image' => 'uploads/products/chocolate_icecream.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Small grape leaves stuffed with labneh',
                'stock' => 100,
                'cost' => 0,
                'price' => 5,
                'compare_price' => null,
                'description' => 'Small grape leaves stuffed with labneh',
                'image' => 'uploads/products/grape_leaves.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Large grape leaves stuffed with labneh',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Large grape leaves stuffed with labneh',
                'image' => 'uploads/products/grape_leaves_large.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Green Kochk Baladi',
                'stock' => 100,
                'cost' => 0,
                'price' => 7,
                'compare_price' => null,
                'description' => 'green kochk baladi',
                'image' => 'uploads/products/green_kochk.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Feta mint',
                'stock' => 100,
                'cost' => 0,
                'price' => 7,
                'compare_price' => null,
                'description' => 'Feta mint',
                'image' => 'uploads/products/feta_mint.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Feta spicy',
                'stock' => 100,
                'cost' => 0,
                'price' => 7,
                'compare_price' => null,
                'description' => 'Feta spicy',
                'image' => 'uploads/products/feta_spicy.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Makdous Medium Spice with walnuts',
                'stock' => 100,
                'cost' => 0,
                'price' => 7,
                'compare_price' => null,
                'description' => 'Makdous Medium Spice with walnuts',
                'image' => 'uploads/products/makdous.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Stuffed olives with labneh',
                'stock' => 100,
                'cost' => 0,
                'price' => 7,
                'compare_price' => null,
                'description' => 'Stuffed olives with labneh',
                'image' => 'uploads/products/olive_labneh.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Hot Spices',
                'stock' => 100,
                'cost' => 0,
                'price' => 7,
                'compare_price' => null,
                'description' => 'Hot Spices',
                'image' => 'uploads/products/chatta.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Zaarour Baladi',
                'stock' => 100,
                'cost' => 0,
                'price' => 5,
                'compare_price' => null,
                'description' => 'Zaarour Baladi',
                'image' => 'uploads/products/zaarour.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Honey Mustard',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Honey Mustard',
                'image' => 'uploads/products/mrtaste_honey_mustard.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Strawbery Syrup',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Strawbery Syrup',
                'image' => 'uploads/products/mrtaste_strawberry_syrup.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Passion Fruit',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Passion Fruit',
                'image' => 'uploads/products/mrtaste_passion_fruit.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Dulce Depleche',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Dulce Depleche',
                'image' => 'uploads/products/mrtaste_dulce_depleche.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste American Burger',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste American Burger',
                'image' => 'uploads/products/mrtaste_american_burger.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Ketchup',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Ketchup',
                'image' => 'uploads/products/mrtaste_ketchup.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Curry Ketchup',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Curry Ketchup',
                'image' => 'uploads/products/mrtaste_curry_ketchup.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Steak Sauce',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Steak Sauce',
                'image' => 'uploads/products/mrtaste_steak_sauce.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Blueberry Syrup',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Blueberry Syrup',
                'image' => 'uploads/products/mrtaste_blueberry_syrup.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Creamy Cheese',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Creamy Cheese',
                'image' => 'uploads/products/mrtaste_creamy_cheese.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Four Cheese',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Four Cheese',
                'image' => 'uploads/products/mrtaste_four_cheese.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Creamy Sriracha',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Creamy Sriracha',
                'image' => 'uploads/products/mrtaste_creamy_sriracha.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Cheddar',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Cheddar',
                'image' => 'uploads/products/mrtaste_cheddar.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Italian',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Italian',
                'image' => 'uploads/products/mrtaste_italian.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Onion & Garlic',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Onion & Garlic',
                'image' => 'uploads/products/mrtaste_onion_garlic.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Honey Free',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Honey Free',
                'image' => 'uploads/products/mrtaste_honey_free.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Mr Taste Date Syrup',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Mr Taste Date Syrup',
                'image' => 'uploads/products/mrtaste_date_syrup.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Pistachio Butter',
                'stock' => 100,
                'cost' => 0,
                'price' => 15,
                'compare_price' => null,
                'description' => 'Pistachio Butter',
                'image' => 'uploads/products/pistachio_butter.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Ketto Nut Butter Mix',
                'stock' => 100,
                'cost' => 0,
                'price' => 5,
                'compare_price' => null,
                'description' => 'Ketto Nut Butter Mix',
                'image' => 'uploads/products/ketto_nut.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Natural Pure',
                'stock' => 100,
                'cost' => 0,
                'price' => 4,
                'compare_price' => null,
                'description' => 'Natural Pure',
                'image' => 'uploads/products/naturale_pure.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Almond Butter',
                'stock' => 100,
                'cost' => 0,
                'price' => 5,
                'compare_price' => null,
                'description' => 'Almond Butter',
                'image' => 'uploads/products/almond_butter.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Maple Peanut Butter',
                'stock' => 100,
                'cost' => 0,
                'price' => 5,
                'compare_price' => null,
                'description' => 'Maple Peanut Butter',
                'image' => 'uploads/products/maple_peanut_butter.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Creamy Peanut Butter',
                'stock' => 100,
                'cost' => 0,
                'price' => 5,
                'compare_price' => null,
                'description' => 'Creamy Peanut Butter',
                'image' => 'uploads/products/creamy_peanut_butter.png',
            ],
            [
                'category_id' => 1,
                'name' => 'Hazelnut Butter',
                'stock' => 100,
                'cost' => 0,
                'price' => 6,
                'compare_price' => null,
                'description' => 'Hazelnut Butter',
                'image' => 'uploads/products/hazelnut_butter.png',
            ],
            [
                'category_id' => 1,
                'name' => 'TeaRapy Relax',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'TeaRapy Relax',
                'image' => 'uploads/products/tearapy_relax.png',
            ],
            [
                'category_id' => 1,
                'name' => 'TeaRapy Active Morning',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'TeaRapy Active Morning',
                'image' => 'uploads/products/tearapy_active_morning.png',
            ],
            [
                'category_id' => 1,
                'name' => 'TeaRapy Immune Booster',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'TeaRapy Immune Booster',
                'image' => 'uploads/products/tearapy_immune_booster.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Wheat Flakes',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Wheat Flakes',
                'image' => 'uploads/products/wheat_flakes.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Organic Coconut Flour',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Organic Coconut Flour',
                'image' => 'uploads/products/organic_coconut_flour.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Organic Chickpea Flour',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Organic Chickpea Flour',
                'image' => 'uploads/products/organic_chickpea_flour.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Organic Potato Starch',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Organic Potato Starch',
                'image' => 'uploads/products/organic_potato_starch.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Organic Turkey Tail Mushroom Powder',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Organic Turkey Tail Mushroom Powder',
                'image' => 'uploads/products/organic_turkey_tail_mushroom_powder.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Organic Chaga Mushroom Powder',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Organic Chaga Mushroom Powder',
                'image' => 'uploads/products/organic_chaga_mushroom_powder.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Gluten Free Baking Powder',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Gluten Free Baking Powder',
                'image' => 'uploads/products/gluten_free_baking_powder.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Almond Flour',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Almond Flour',
                'image' => 'uploads/products/almond_flour.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Organic Cordyceps Mushroom Powder',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Organic Cordyceps Mushroom Powder',
                'image' => 'uploads/products/organic_cordyceps_mushroom_powder.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Organic Brown Flaxseed Meal',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Organic Brown Flaxseed Meal',
                'image' => 'uploads/products/organic_brown_flaxseed_meal.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Organic Golden Flax Seeds',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Organic Golden Flax Seeds',
                'image' => 'uploads/products/organic_golden_flax_seeds.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Organic Cacao Powder',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Organic Cacao Powder',
                'image' => 'uploads/products/organic_cacao_powder.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Organic Carob Powder',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Organic Carob Powder',
                'image' => 'uploads/products/organic_carob_powder.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Organic Raw Cacao Nibs',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Organic Raw Cacao Nibs',
                'image' => 'uploads/products/organic_raw_cacao_nibs.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Organic Brown Flax Seeds',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Organic Brown Flax Seeds',
                'image' => 'uploads/products/organic_brown_flax_seeds.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Organic Red Reishi Mushroom Powder',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Organic Red Reishi Mushroom Powder',
                'image' => 'uploads/products/organic_red_reishi_mushroom_powder.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Organic Goji Berries',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Organic Goji Berries',
                'image' => 'uploads/products/organic_goji_berries.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Organic Vital Wheat Gluten',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Organic Vital Wheat Gluten',
                'image' => 'uploads/products/organic_vital_wheat_gluten.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Organic Sunflower Seeds',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Organic Sunflower Seeds',
                'image' => 'uploads/products/organic_sunflower_seeds.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Organic Rice Milk Powder',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Organic Rice Milk Powder',
                'image' => 'uploads/products/organic_rice_milk_powder.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Organic Turmeric Powder',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Organic Turmeric Powder',
                'image' => 'uploads/products/organic_tuemeric_powder.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Organic Instant Barley Drink',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Organic Instant Barley Drink',
                'image' => 'uploads/products/organic_instant_barley_drink.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Organic Instant Cocoa Drink',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Organic Instant Cocoa Drink',
                'image' => 'uploads/products/organic_instant_cocoa_drink.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Organic Matcha Tea',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Organic Matcha Tea',
                'image' => 'uploads/products/organic_matcha_tea.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Mushroom Coffee',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Mushroom Coffee',
                'image' => 'uploads/products/mushroom_coffee.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Organic Chlorella Powder',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Organic Chlorella Powder',
                'image' => 'uploads/products/organic_chlorella_powder.png',
            ],
            [
                'category_id' => 9,
                'name' => 'Organic Lion Mane Mushroom Powder',
                'stock' => 100,
                'cost' => 0,
                'price' => 0,
                'compare_price' => null,
                'description' => 'Organic Lion Mane Mushroom Powder',
                'image' => 'uploads/products/organic_lion_mane_mushroom_powder.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Peanut butter with chocolate',
                'stock' => 100,
                'cost' => 0,
                'price' => 4,
                'compare_price' => null,
                'description' => 'Peanut butter with chocolate',
                'image' => 'uploads/products/peanut_butter_with_chocolate.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Dark chocolate',
                'stock' => 100,
                'cost' => 0,
                'price' => 4,
                'compare_price' => null,
                'description' => 'Dark chocolate',
                'image' => 'uploads/products/dark_chocolate.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Strawberry Jam',
                'stock' => 100,
                'cost' => 0,
                'price' => 6,
                'compare_price' => null,
                'description' => 'Strawberry Jam',
                'image' => 'uploads/products/strawberry_jam.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Red Fruits Jam',
                'stock' => 100,
                'cost' => 0,
                'price' => 6,
                'compare_price' => null,
                'description' => 'Red Fruits Jam',
                'image' => 'uploads/products/red_fruits_jam.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Apricot Jam',
                'stock' => 100,
                'cost' => 0,
                'price' => 6,
                'compare_price' => null,
                'description' => 'Apricot Jam',
                'image' => 'uploads/products/apricot_jam.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Zero Calorie Sweetener',
                'stock' => 100,
                'cost' => 0,
                'price' => 6,
                'compare_price' => null,
                'description' => 'Zero Calorie Sweetener',
                'image' => 'uploads/products/zero_calorie_sweetener.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Chocolate Spread',
                'stock' => 100,
                'cost' => 0,
                'price' => 6,
                'compare_price' => null,
                'description' => 'Chocolate Spread',
                'image' => 'uploads/products/chocolate_spread.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Coffee n Mylk',
                'stock' => 100,
                'cost' => 0,
                'price' => 9,
                'compare_price' => null,
                'description' => 'Coffee n Mylk no added sugar, With coconut milk, Sugar free, Dairy free, Gluteen free, Lactose free.',
                'image' => 'uploads/products/coffee_milk.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Moringa Hot Chocolate',
                'stock' => 100,
                'cost' => 0,
                'price' => 9,
                'compare_price' => null,
                'description' => 'Moringa Hot Chocolate no added sugar, With coconut milk, Sugar free, Dairy free, Gluteen free, Lactose free.',
                'image' => 'uploads/products/moringa_hot_chocolate.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Mocca Dark Coffee',
                'stock' => 100,
                'cost' => 0,
                'price' => 9,
                'compare_price' => null,
                'description' => 'Mocca Dark Coffee no added sugar, With coconut milk, Sugar free, Dairy free, Gluteen free, Lactose free.',
                'image' => 'uploads/products/mocca_dark_coffee.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Hot Chocolate',
                'stock' => 100,
                'cost' => 0,
                'price' => 9,
                'compare_price' => null,
                'description' => 'Hot Chocolate no added sugar, With coconut milk, Sugar free, Dairy free, Gluteen free, Lactose free.',
                'image' => 'uploads/products/hot_chocolate.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Keto white chocolate',
                'stock' => 100,
                'cost' => 0,
                'price' => 9,
                'compare_price' => null,
                'description' => 'Keto white chocolate: Sugar free, Dairy free, Gluten free.',
                'image' => 'uploads/products/keto_white_chocolate.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Milk chocolate keto spread',
                'stock' => 100,
                'cost' => 0,
                'price' => 9,
                'compare_price' => null,
                'description' => 'Milk chocolate keto spread',
                'image' => 'uploads/products/milk_chocolate_keto_spread.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Keto chocolate spread dark',
                'stock' => 100,
                'cost' => 0,
                'price' => 9,
                'compare_price' => null,
                'description' => 'Keto chocolate spread dark',
                'image' => 'uploads/products/keto_chocolate_spread_dark.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Honey Rice Balls',
                'stock' => 100,
                'cost' => 0,
                'price' => 3,
                'compare_price' => null,
                'description' => 'Honey Rice Balls: Sugar free, Dairy free, Vegan, Gluteen free.',
                'image' => 'uploads/products/honey_rice_balls.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Chocolate Rice Balls',
                'stock' => 100,
                'cost' => 0,
                'price' => 3,
                'compare_price' => null,
                'description' => 'Chocolate Rice Balls: Sugar free, Dairy free, Vegan, Gluteen free.',
                'image' => 'uploads/products/honey_rice_balls.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Maple syrup organic ',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Maple syrup organic',
                'image' => 'uploads/products/maple_syrup_organic.png',
            ],
            [
                'category_id' => 6,
                'name' => 'MCT Oil ',
                'stock' => 100,
                'cost' => 0,
                'price' => 15,
                'compare_price' => null,
                'description' => 'MCT Oil: Keto, Organic',
                'image' => 'uploads/products/mct_oil.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Black Seeds Organic ',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Black Seeds Organic',
                'image' => 'uploads/products/black_seeds_organic.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Flax Seeds Oil Organic ',
                'stock' => 100,
                'cost' => 0,
                'price' => 7,
                'compare_price' => null,
                'description' => 'Flax Seeds Oil Organic',
                'image' => 'uploads/products/flax_seeds_oil_organic.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Extra Virgin Avocado Oil ',
                'stock' => 100,
                'cost' => 0,
                'price' => 12,
                'compare_price' => null,
                'description' => 'Extra Virgin Avocado Oil: Organic, keto, Cold Pressed.',
                'image' => 'uploads/products/extra_virgin_avocado_oil.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Maple syrup organic ',
                'stock' => 100,
                'cost' => 0,
                'price' => 10,
                'compare_price' => null,
                'description' => 'Maple syrup organic',
                'image' => 'uploads/products/maple_syrup_organic.png',
            ],

        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
